Repository angular/universal, pull requests merged in 2018-06, with the labels that each got.

#1006 docs: refactor READMEs
  README.md
  UPGRADE-GUIDE.md
  docs/angular2-universal-migration.md
  docs/gotchas.md
  docs/transfer-http.md
  modules/common/README.md
Labels: cla: yes

#1008 build: upgrade bazel to latest
  .circleci/config.yml
  BUILD.bazel
  WORKSPACE
  modules/common/BUILD.bazel
  package.json
  yarn.lock
Labels: cla: yes

#1009 fix(common): remove internal monicker for FileLoader
  modules/common/src/common-engine/file-loader.ts
Labels: PR action: review, PR target: master only, cla: yes, comp: common

#1011 refactor: clean up BUILD files imports/exports
  modules/aspnetcore-engine/BUILD.bazel
  modules/aspnetcore-engine/tokens/BUILD.bazel
  modules/common/BUILD.bazel
  modules/express-engine/BUILD.bazel
  modules/hapi-engine/BUILD.bazel
  modules/hapi-engine/tokens/BUILD.bazel
  modules/module-map-ngfactory-loader/BUILD.bazel
Labels: cla: yes

#1014 chore: introduce GitHub Issue and Pull Request templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATES/Bug.md
  .github/ISSUE_TEMPLATES/Feature_Request.md
  .github/ISSUE_TEMPLATES/Proposal.md
  .github/PULL_REQUEST_TEMPLATES/Improvement.md
  .github/PULL_REQUEST_TEMPLATES/New_Feature.md
Labels: PR action: review, PR target: master only, cla: yes, comp: docs

#1016 chore: fix up maths for Github templates
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .github/ISSUE_TEMPLATE/Proposal.md
  .github/PULL_REQUEST_TEMPLATE/Improvement.md
  .github/PULL_REQUEST_TEMPLATE/New_Feature.md
Labels: cla: yes

#1017 fix(common): fixup secondary entrypoints
  modules/common/engine/BUILD.bazel
  modules/common/tokens/BUILD.bazel
Labels: cla: yes

#1020 ci: increase resources for testing
  .circleci/config.yml
  .github/CODEOWNERS
Labels: PR action: review, PR target: master only, cla: yes, comp: ci

#1026 docs: Fix link to module-map-ngfactory-loader
  README.md
Labels: cla: yes
