Repository angular/universal, pull requests merged in 2018-04, with the labels that each got.

#948 feat(common): enable StateTransferInitializerModule
  modules/common/public-api.ts
Labels: PR action: review, PR target: master only, cla: yes, comp: common

#947 chore: upgrade to v6
  WORKSPACE
  angular.tsconfig.json
  modules/aspnetcore-engine/package.json
  modules/aspnetcore-engine/src/platform-server-utils.ts
  modules/common/src/transfer_http.ts
  package.json
  tools/defaults.bzl
  tools/package-tools/rollup-globals.ts
  tslint.json
  yarn.lock
Labels: PR action: review, PR target: master only, cla: yes, comp: build

#952 Fix import of REQUEST token
  modules/aspnetcore-engine/README.md
  modules/express-engine/README.md
  modules/hapi-engine/README.md
Labels: PR action: merge, PR state: LGTM, cla: yes, comp: build

#961 build: update to bazel 11.1
  .circleci/config.yml
  .travis.yml
  WORKSPACE
  package.json
  yarn.lock
Labels: PR state: WIP, cla: yes

#962 build: remove legacy testing infra
  .travis.yml
  modules/aspnetcore-engine/tsconfig.spec.json
  modules/common/tsconfig.spec.json
  modules/express-engine/tsconfig.spec.json
  modules/hapi-engine/tsconfig.spec.json
  modules/module-map-ngfactory-loader/tsconfig.spec.json
  package.json
  test/jasmine.conf.json
  test/karma-test-shim.js
  test/karma.conf.js
  test/patch-testbed.js
  test/test-browser.ts
  test/test-server.ts
Labels: cla: yes

#963 test: rename public-api to public_api
  .travis.yml
  modules/aspnetcore-engine/tokens/tsconfig.lib.json
  modules/aspnetcore-engine/tsconfig.lib.json
  modules/common/tsconfig.lib.json
  modules/express-engine/tokens/tsconfig.lib.json
  modules/express-engine/tsconfig.lib.json
  modules/hapi-engine/tokens/tsconfig.lib.json
  modules/hapi-engine/tsconfig.lib.json
  modules/module-map-ngfactory-loader/tsconfig.lib.json
  scripts/ci/README.md
  scripts/ci/sources/mode.sh
  scripts/ci/travis-script.sh
Labels: cla: yes

#953 test(express-engine): add basic unit tests
  modules/express-engine/BUILD.bazel
  modules/express-engine/spec/index.spec.ts
  tools/package-tools/rollup-globals.ts
  tsconfig.json
  tslint.json
  yarn.lock
Labels: PR action: merge, PR target: master only, cla: yes, comp: build

#970 docs: reduce uneeded info in issue/pr templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#971 build: remove old build system
  .travis.yml
  build-config.js
  build-test.ts
  build.sh
  build.ts
  modules/aspnetcore-engine/tokens/tsconfig.lib.json
  modules/aspnetcore-engine/tsconfig.lib.json
  modules/common/tsconfig.lib.json
  modules/express-engine/tokens/tsconfig.lib.json
  modules/express-engine/tsconfig.lib.json
  modules/hapi-engine/tokens/tsconfig.lib.json
  modules/hapi-engine/tsconfig.lib.json
  modules/module-map-ngfactory-loader/tsconfig.lib.json
  tools/package-tools/build-bundles.ts
  tools/package-tools/build-config.ts
  tools/package-tools/build-package.ts
  tools/package-tools/build-release.ts
  tools/package-tools/compile-entry-point.ts
  tools/package-tools/copy-files.ts
  tools/package-tools/entry-point-package-json.ts
  tools/package-tools/index.ts
  tools/package-tools/metadata-inlining.ts
  tools/package-tools/metadata-reexport.ts
  tools/package-tools/minify-sources.ts
  tools/package-tools/ngc-compile.ts
  tools/package-tools/packages.ts
  tools/package-tools/rollup-globals.ts
  tools/package-tools/rollup-remove-licenses.ts
  tools/package-tools/secondary-entry-points.ts
  tools/package-tools/sourcemap-remap.ts
  tools/package-tools/typings-reexport.ts
  tools/package-tools/version-placeholders.ts
  tools/tslint-rules/missingRollupGlobalsRule.ts
  tools/tslint-rules/requireLicenseBannerRule.ts
  tools/tslint-rules/tsLoaderRule.js
  tools/tslint-rules/tsconfig.json
  tslint.json
Labels: cla: yes
