Repository angular/universal, pull requests merged in 2018-03, with the labels that each got.

#893 Changelog
  CHANGELOG.md
  package.json
  yarn.lock
Labels: PR action: review, cla: yes

#919 docs(express, hapi): fix token import example
  modules/express-engine/README.md
  modules/hapi-engine/README.md
Labels: cla: yes

#909 build: introduce bazel
  .cicleci/config.yml
  .circleci/config.yml
  .gitignore
  BUILD.bazel
  WORKSPACE
  angular.tsconfig.json
  modules/aspnetcore-engine/BUILD.bazel
  modules/aspnetcore-engine/spec/index.spec.ts
  modules/common/BUILD.bazel
  modules/common/spec/index.spec.ts
  modules/express-engine/BUILD.bazel
  modules/express-engine/spec/index.spec.ts
  modules/hapi-engine/BUILD.bazel
  modules/hapi-engine/spec/index.spec.ts
  modules/module-map-ngfactory-loader/BUILD.bazel
  modules/module-map-ngfactory-loader/spec/index.spec.ts
  package.json
  tools/BUILD.bazel
  tools/bazel.rc
  tools/defaults.bzl
  tsconfig.json
  yarn.lock
Labels: PR target: master only, cla: yes, comp: build

#921 chore: update CHANGELOG with breaking changes
  CHANGELOG.md
Labels: PR action: review, cla: yes

#926 build: lint bazel build files
  .circleci/config.yml
  BUILD.bazel
  modules/aspnetcore-engine/BUILD.bazel
  modules/common/BUILD.bazel
  modules/express-engine/BUILD.bazel
  modules/hapi-engine/BUILD.bazel
  modules/module-map-ngfactory-loader/BUILD.bazel
Labels: PR action: review, PR target: master only, cla: yes

#924 build: store build artifacts
  .circleci/config.yml
Labels: PR action: review, PR target: master only, cla: yes

#916 feat(common): introduce StateTransferInitializerModule
  modules/common/public-api.ts
  modules/common/src/state-transfer-initilizer/README.md
  modules/common/src/state-transfer-initilizer/module.ts
Labels: PR action: review, PR target: master only, cla: yes

#928 docs(README): rename "Angular 2" to "Angular"
  README.md
Labels: cla: yes

#930 build: re-introduce build.sh
  build.sh
  modules/aspnetcore-engine/public-api.ts
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/tokens.ts
  modules/aspnetcore-engine/tsconfig.fortokens.json
  modules/common/public-api.ts
  modules/express-engine/public-api.ts
  modules/express-engine/src/main.ts
  modules/express-engine/tokens.ts
  modules/express-engine/tsconfig.fortokens.json
  modules/hapi-engine/public-api.ts
  modules/hapi-engine/src/main.ts
  modules/hapi-engine/tokens.ts
  modules/hapi-engine/tsconfig.fortokens.json
  publish.sh
Labels: PR action: review, PR target: 5.x & master, cla: yes

#933 build: add globals to bazel
  tools/defaults.bzl
  tools/package-tools/rollup-globals.ts
Labels: PR action: review, cla: yes

#940 build(lib): fix secondary entrypoints and bundle with APF v5
  build-config.js
  build-test.ts
  build.ts
  modules/aspnetcore-engine/package.json
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/tokens/index.ts
  modules/aspnetcore-engine/tokens/public-api.ts
  modules/aspnetcore-engine/tokens/tokens.ts
  modules/aspnetcore-engine/tokens/tsconfig.lib.json
  modules/aspnetcore-engine/tsconfig.fortokens.json
  modules/aspnetcore-engine/tsconfig.lib.json
  modules/aspnetcore-engine/tsconfig.spec.json
  modules/common/package.json
  modules/common/tsconfig.lib.json
  modules/common/tsconfig.spec.json
  modules/express-engine/package.json
  modules/express-engine/src/main.ts
  modules/express-engine/tokens/index.ts
  modules/express-engine/tokens/public-api.ts
  modules/express-engine/tokens/tokens.ts
  modules/express-engine/tokens/tsconfig.lib.json
  modules/express-engine/tsconfig.fortokens.json
  modules/express-engine/tsconfig.lib.json
  modules/express-engine/tsconfig.spec.json
  modules/hapi-engine/package.json
  modules/hapi-engine/src/main.ts
  modules/hapi-engine/tokens/index.ts
  modules/hapi-engine/tokens/public-api.ts
  modules/hapi-engine/tokens/tokens.ts
  modules/hapi-engine/tokens/tsconfig.lib.json
  modules/hapi-engine/tsconfig.fortokens.json
  modules/hapi-engine/tsconfig.lib.json
  modules/hapi-engine/tsconfig.spec.json
  modules/module-map-ngfactory-loader/package.json
  modules/module-map-ngfactory-loader/tsconfig.lib.json
  modules/module-map-ngfactory-loader/tsconfig.spec.json
  package.json
  publish.sh
  tools/package-tools/build-bundles.ts
  tools/package-tools/build-package.ts
  tools/package-tools/build-release.ts
  tools/package-tools/compile-entry-point.ts
  tools/package-tools/copy-files.ts
  tools/package-tools/entry-point-package-json.ts
  tools/package-tools/index.ts
  tools/package-tools/metadata-inlining.ts
  tools/package-tools/metadata-reexport.ts
  tools/package-tools/minify-sources.ts
  tools/package-tools/ngc-compile.ts
  tools/package-tools/packages.ts
  tools/package-tools/rollup-globals.ts
  tools/package-tools/rollup-remove-licenses.ts
  tools/package-tools/secondary-entry-points.ts
  tools/package-tools/sourcemap-remap.ts
  tools/package-tools/typings-reexport.ts
  tools/package-tools/version-placeholders.ts
  tsconfig.json
  yarn.lock
Labels: PR action: merge, PR state: LGTM, PR target: 5.x & master, cla: yes, comp: build
