Repository angular/universal, pull requests merged in 2018-02, with the labels that each got.

#876 chore: bump year
  LICENSE
Labels: pr_action: review

#889 fix(aspnetcore-engine): fix ServerTransferStateModule and TransferState
  modules/aspnetcore-engine/index.ts
  modules/aspnetcore-engine/src/create-transfer-script.ts
  modules/aspnetcore-engine/src/interfaces/engine-render-result.ts
  modules/aspnetcore-engine/src/interfaces/request-params.ts
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/src/platform-server-utils.ts
Labels: pr_action: merge, pr_state: LGTM

#871 docs(readme): update roadmap
  README.md
Labels: pr_action: cleanup, pr_state: LGTM

#864 docs(readme.md): added a missing space
  README.md
Labels: pr_action: cleanup, pr_state: LGTM

#853 fix(express-engine): node 9 strict engine error
  modules/express-engine/package.json
Labels: cla: yes, pr_state: LGTM

#891 feat(build): add unit testing with karma
  karma.conf.js
  modules/index.spec.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: cla: yes, pr_state: LGTM

#908 build(lint): add linting using tslint with custom rules
  .travis.yml
  build-config.js
  build-test.js
  build-test.ts
  build.js
  build.ts
  modules/aspnetcore-engine/index.ts
  modules/aspnetcore-engine/public-api.ts
  modules/aspnetcore-engine/src/create-transfer-script.ts
  modules/aspnetcore-engine/src/file-loader.ts
  modules/aspnetcore-engine/src/interfaces/engine-options.ts
  modules/aspnetcore-engine/src/interfaces/engine-render-result.ts
  modules/aspnetcore-engine/src/interfaces/request-params.ts
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/src/platform-server-utils.ts
  modules/aspnetcore-engine/src/tokens.ts
  modules/common/index.ts
  modules/common/public-api.ts
  modules/common/src/transfer_http.spec.ts
  modules/common/src/transfer_http.ts
  modules/express-engine/index.ts
  modules/express-engine/public-api.ts
  modules/express-engine/src/file-loader.ts
  modules/express-engine/src/main.ts
  modules/express-engine/src/tokens.ts
  modules/hapi-engine/index.ts
  modules/hapi-engine/public-api.ts
  modules/hapi-engine/src/file-loader.ts
  modules/hapi-engine/src/main.ts
  modules/hapi-engine/src/tokens.ts
  modules/module-map-ngfactory-loader/index.ts
  modules/module-map-ngfactory-loader/public-api.ts
  modules/module-map-ngfactory-loader/src/index.ts
  modules/module-map-ngfactory-loader/src/module-map-loader.module.ts
  modules/module-map-ngfactory-loader/src/module-map-ngfactory-loader.ts
  modules/module-map-ngfactory-loader/src/module-map.ts
  package.json
  tools/package-tools/build-config.ts
  tools/package-tools/build-package.ts
  tools/package-tools/index.ts
  tools/package-tools/rollup-globals.ts
  tools/tsconfig.json
  tools/tslint-rules/deletionTargetRule.ts
  tools/tslint-rules/missingRollupGlobalsRule.ts
  tools/tslint-rules/noExposedTodoRule.ts
  tools/tslint-rules/noRxjsPatchImportsRule.ts
  tools/tslint-rules/requireLicenseBannerRule.ts
  tools/tslint-rules/tsLoaderRule.js
  tslint.json
  yarn.lock
Labels: PR action: review, cla: yes, comp: build

#899 chore: update PR/issue template and add codeowners template
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR action: review, cla: yes

#810 feat(engines): add optional url and document to render options
  modules/aspnetcore-engine/README.md
  modules/aspnetcore-engine/src/interfaces/engine-options.ts
  modules/aspnetcore-engine/src/main.ts
  modules/express-engine/README.md
  modules/express-engine/src/main.ts
  modules/hapi-engine/README.md
  modules/hapi-engine/src/main.ts
Labels: PR action: review, cla: yes

#875 docs(readme): wrong express syntax
  modules/express-engine/README.md
Labels: PR state: LGTM, cla: no
