Repository angular/universal, pull requests merged in 2019-09, with the labels that each got.

#1224 chore: set up automatic locking of stale closed issues
  .github/workflows/lock-closed.yml
Labels: PR action: merge, cla: yes

#1225 Update to latest commit of lock closed github action
  .github/workflows/lock-closed.yml
Labels: cla: yes

#1226 chore: bump number of locks per lock-closed bot run to 100
  .github/workflows/lock-closed.yml
Labels: cla: yes

#1227 style: force LF as linebreak-style when checking out the repo
  .gitattributes
Labels: cla: yes

#1228 ci: move to latest lock-closed commit for github action
  .github/workflows/lock-closed.yml
Labels: PR action: merge, PR target: master only, cla: yes

#1229 fix(express-engine): add missing `@types/express` for express
  modules/express-engine/schematics/install/index.ts
  tools/defaults.bzl
Labels: cla: yes

#1230 [patch] fix(express-engine): add missing `@types/express` for express
  modules/express-engine/schematics/install/index.ts
  tools/defaults.bzl
Labels: cla: yes

#1240 build: update nodejs rules to 0.37.0 and enable managed_directories
  .bazelrc
  WORKSPACE
Labels: cla: yes

#1241 fix(common): don't run universal schematic if server target already e…
  integration/express-engine-ivy/angular.json
  integration/express-engine-ve/angular.json
  integration/hapi-engine-ivy/angular.json
  integration/hapi-engine-ve/angular.json
  modules/common/schematics/install/index.spec.ts
  modules/common/schematics/install/index.ts
Labels: cla: yes

#1246 refactor(express-engine, hapi-engine): use CommonEngine
  modules/aspnetcore-engine/src/main.ts
  modules/common/engine/src/engine.ts
  modules/express-engine/BUILD.bazel
  modules/express-engine/src/main.ts
  modules/hapi-engine/BUILD.bazel
  modules/hapi-engine/src/main.ts
  package.json
Labels: cla: yes

#1247 fix(express-engine): export Express app from server.ts
  integration/express-engine-ivy/server.ts
  integration/express-engine-ve/server.ts
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: cla: yes

#1249 fix(hapi-engine, express-engine): export app for serverless functions
  integration/express-engine-ivy/server.ts
  integration/express-engine-ve/server.ts
  integration/hapi-engine-ivy/server.ts
  integration/hapi-engine-ve/server.ts
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
  modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: cla: yes

#1250 tests: update optimization setting for integration tests
  integration/express-engine-ivy/angular.json
  integration/express-engine-ve/angular.json
  integration/hapi-engine-ivy/angular.json
  integration/hapi-engine-ve/angular.json
Labels: cla: yes

#1252 fix(express-engine): set APP_BASE_HREF to req.baseUrl
  integration/express-engine-ivy/server.ts
  integration/express-engine-ve/server.ts
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: cla: yes

#1253 chore: clean up package.json
  package.json
  yarn.lock
Labels: cla: yes

#1258 ci: add `--silent` to yarn install
  integration/run_tests.sh
Labels: cla: yes

#1256 Builders package skeleton
  modules/builders/BUILD.bazel
  modules/builders/README.md
  modules/builders/builders.json
  modules/builders/package.json
  modules/builders/src/index.ts
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/schema.json
  modules/builders/src/ssr-dev-server/schema.ts
  package.json
  yarn.lock
Labels: cla: yes

#1259 fix(builders): fix package.json
  modules/builders/BUILD.bazel
  modules/builders/package.json
  tools/defaults.bzl
Labels: cla: yes

#1262 chore: unpin @angular package deps
  integration/common/package.json
  integration/express-engine-ivy/package.json
  integration/express-engine-ve/package.json
  integration/hapi-engine-ivy/package.json
  integration/hapi-engine-ve/package.json
  integration/module-map-ngfactory-loader/README.md
  integration/module-map-ngfactory-loader/build.sh
  integration/module-map-ngfactory-loader/e2e/helloworld-spec.ts
  integration/module-map-ngfactory-loader/e2e/protractor.config.js
  integration/module-map-ngfactory-loader/e2e/tsconfig.json
  integration/module-map-ngfactory-loader/e2e/util.ts
  integration/module-map-ngfactory-loader/package.json
  integration/module-map-ngfactory-loader/src/helloworld/app.server.ts
  integration/module-map-ngfactory-loader/src/helloworld/app.ts
  integration/module-map-ngfactory-loader/src/helloworld/client.ts
  integration/module-map-ngfactory-loader/src/helloworld/hello-world.component.ts
  integration/module-map-ngfactory-loader/src/helloworld/index.html
  integration/module-map-ngfactory-loader/src/helloworld/lazy.module.ts
  integration/module-map-ngfactory-loader/src/server.ts
  integration/module-map-ngfactory-loader/tsconfig.json
  integration/module-map-ngfactory-loader/webpack.client.config.js
  integration/module-map-ngfactory-loader/webpack.server.config.js
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes

#1264 refactor(common): remove redundant `npm run build:client-and-server-b…
  modules/common/schematics/install/index.ts
Labels: PR target: master only, cla: yes, comp: common
