Repository angular/universal, pull requests merged in 2019-12, with the labels that each got.

#1350 chore: update deps
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes

#1353 fix(builders): remove cache-control header from responses
  modules/builders/src/ssr-dev-server/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1351 fix(builders): log message when compilation is ended successfully
  modules/builders/src/ssr-dev-server/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1356 fix(builders): display server console message
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/utils.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1361 build: exclude schematics `testing` folder from being shipped
  modules/common/schematics/BUILD.bazel
  modules/common/schematics/testing/test-app.ts
  modules/express-engine/schematics/BUILD.bazel
  modules/express-engine/schematics/testing/test-app.ts
  modules/hapi-engine/schematics/BUILD.bazel
  modules/hapi-engine/schematics/testing/test-app.ts
Labels: PR target: master-only, cla: yes

#1357 feat(builders): implement prerender
  modules/builders/BUILD.bazel
  modules/builders/builders.json
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/schema.json
  modules/builders/src/prerender/schema.ts
Labels: cla: yes

#1360 fix(builder): add option to provide a custom host
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/schema.json
  modules/builders/src/ssr-dev-server/schema.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1364 fix(common): use shorter name to start the ssr-dev-server
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
Labels: PR target: master-only, cla: yes, comp: common

#1366 fix(builder): update prerender error message
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
Labels: cla: yes

#1365 feat(prerender): config preredner in ng add
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
Labels: cla: yes

#1370 chore: update deps
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: cla: yes

#1378 test: add e2e test for prerender builder
  integration/express-engine-ivy-prerender/README.md
  integration/express-engine-ivy-prerender/angular.json
  integration/express-engine-ivy-prerender/browserslist
  integration/express-engine-ivy-prerender/e2e/protractor.conf.js
  integration/express-engine-ivy-prerender/e2e/src/app.e2e-spec.ts
  integration/express-engine-ivy-prerender/e2e/src/app.po.ts
  integration/express-engine-ivy-prerender/e2e/tsconfig.json
  integration/express-engine-ivy-prerender/karma.conf.js
  integration/express-engine-ivy-prerender/package.json
  integration/express-engine-ivy-prerender/server.ts
  integration/express-engine-ivy-prerender/src/app/app-routing.module.ts
  integration/express-engine-ivy-prerender/src/app/app.component.css
  integration/express-engine-ivy-prerender/src/app/app.component.html
  integration/express-engine-ivy-prerender/src/app/app.component.spec.ts
  integration/express-engine-ivy-prerender/src/app/app.component.ts
  integration/express-engine-ivy-prerender/src/app/app.module.ts
  integration/express-engine-ivy-prerender/src/app/app.server.module.ts
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.css
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.html
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.spec.ts
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.ts
  integration/express-engine-ivy-prerender/src/app/pokemon.service.spec.ts
  integration/express-engine-ivy-prerender/src/app/pokemon.service.ts
  integration/express-engine-ivy-prerender/src/assets/.gitkeep
  integration/express-engine-ivy-prerender/src/environments/environment.prod.ts
  integration/express-engine-ivy-prerender/src/environments/environment.ts
  integration/express-engine-ivy-prerender/src/favicon.ico
  integration/express-engine-ivy-prerender/src/index.html
  integration/express-engine-ivy-prerender/src/main.server.ts
  integration/express-engine-ivy-prerender/src/main.ts
  integration/express-engine-ivy-prerender/src/polyfills.ts
  integration/express-engine-ivy-prerender/src/styles.css
  integration/express-engine-ivy-prerender/src/test.ts
  integration/express-engine-ivy-prerender/static-server.js
  integration/express-engine-ivy-prerender/tsconfig.app.json
  integration/express-engine-ivy-prerender/tsconfig.json
  integration/express-engine-ivy-prerender/tsconfig.server.json
  integration/express-engine-ivy-prerender/tsconfig.spec.json
Labels: cla: yes

#1381 fix(builder): allow prerender of nested paths
  integration/express-engine-ivy-prerender/e2e/protractor.conf.js
  integration/express-engine-ivy-prerender/e2e/src/app.e2e-spec.ts
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.ts
  integration/express-engine-ivy-prerender/src/app/pokemon.service.ts
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
Labels: cla: yes

#1383 fix(builder): store index.html as index.original.html when prerendering '/'
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
Labels: cla: yes

#1382 fix(common): add production config section to prerender builder config
  modules/common/schematics/add/index.ts
Labels: cla: yes

#1384 Feat/mark prerendered routes
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1385 fix(schematics): use index.original.html if it exists
  integration/express-engine-ivy-prerender/angular.json
  integration/express-engine-ivy-prerender/e2e/protractor.conf.js
  integration/express-engine-ivy-prerender/e2e/src/app.e2e-spec.ts
  integration/express-engine-ivy-prerender/e2e/src/app.po.ts
  integration/express-engine-ivy-prerender/package.json
  integration/express-engine-ivy-prerender/server.ts
  integration/express-engine-ivy-prerender/src/app/app-routing.module.ts
  integration/express-engine-ivy-prerender/src/app/app.component.css
  integration/express-engine-ivy-prerender/src/app/app.component.html
  integration/express-engine-ivy-prerender/src/app/app.component.spec.ts
  integration/express-engine-ivy-prerender/src/app/app.component.ts
  integration/express-engine-ivy-prerender/src/app/app.module.ts
  integration/express-engine-ivy-prerender/src/app/homepage.component.ts
  integration/express-engine-ivy-prerender/src/app/pokedex.component.ts
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.css
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.html
  integration/express-engine-ivy-prerender/src/app/pokedex/pokedex.component.spec.ts
  integration/express-engine-ivy-prerender/src/app/pokemon.service.spec.ts
  integration/express-engine-ivy/server.ts
  integration/express-engine-ve/server.ts
  integration/hapi-engine-ivy/server.ts
  integration/hapi-engine-ve/server.ts
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
  modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: cla: yes

#1248 feat(common): set RouterModule initialNavigation in schematics
  integration/hapi-engine-ve/angular.json
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
  modules/common/schematics/utils/utils.ts
  package.json
Labels: PR target: master-only, cla: yes, comp: common

#1389 Update README.md
  README.md
Labels: PR target: master-only, cla: yes

#1362 ci: add bazel builder testing infra
  modules/builders/BUILD.bazel
  modules/builders/src/index.ts
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/schema.json
  modules/builders/src/prerender/schema.ts
  modules/builders/src/ssr-dev-server/index.spec.ts
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/utils.ts
  modules/builders/testing/hello-world-app/README.md
  modules/builders/testing/hello-world-app/angular.json
  modules/builders/testing/hello-world-app/browserslist
  modules/builders/testing/hello-world-app/e2e/protractor.conf.js
  modules/builders/testing/hello-world-app/e2e/src/app.e2e-spec.ts
  modules/builders/testing/hello-world-app/e2e/src/app.po.ts
  modules/builders/testing/hello-world-app/e2e/tsconfig.json
  modules/builders/testing/hello-world-app/karma.conf.js
  modules/builders/testing/hello-world-app/package.json
  modules/builders/testing/hello-world-app/server.ts
  modules/builders/testing/hello-world-app/src/app/app-routing.module.ts
  modules/builders/testing/hello-world-app/src/app/app.component.css
  modules/builders/testing/hello-world-app/src/app/app.component.html
  modules/builders/testing/hello-world-app/src/app/app.component.spec.ts
  modules/builders/testing/hello-world-app/src/app/app.component.ts
  modules/builders/testing/hello-world-app/src/app/app.module.ts
  modules/builders/testing/hello-world-app/src/app/app.server.module.ts
  modules/builders/testing/hello-world-app/src/app/foo-bar/foo-bar.component.css
  modules/builders/testing/hello-world-app/src/app/foo-bar/foo-bar.component.html
  modules/builders/testing/hello-world-app/src/app/foo-bar/foo-bar.component.spec.ts
  modules/builders/testing/hello-world-app/src/app/foo-bar/foo-bar.component.ts
  modules/builders/testing/hello-world-app/src/app/foo/foo.component.css
  modules/builders/testing/hello-world-app/src/app/foo/foo.component.html
  modules/builders/testing/hello-world-app/src/app/foo/foo.component.spec.ts
  modules/builders/testing/hello-world-app/src/app/foo/foo.component.ts
  modules/builders/testing/hello-world-app/src/assets/.gitkeep
  modules/builders/testing/hello-world-app/src/environments/environment.prod.ts
  modules/builders/testing/hello-world-app/src/environments/environment.ts
  modules/builders/testing/hello-world-app/src/favicon.ico
  modules/builders/testing/hello-world-app/src/index.html
  modules/builders/testing/hello-world-app/src/main.server.ts
  modules/builders/testing/hello-world-app/src/main.ts
  modules/builders/testing/hello-world-app/src/polyfills.ts
  modules/builders/testing/hello-world-app/src/styles.css
  modules/builders/testing/hello-world-app/src/test.ts
  modules/builders/testing/hello-world-app/tsconfig.app.json
  modules/builders/testing/hello-world-app/tsconfig.json
  modules/builders/testing/hello-world-app/tsconfig.server.json
  modules/builders/testing/hello-world-app/tsconfig.spec.json
  modules/builders/testing/hello-world-app/tslint.json
  modules/builders/testing/utils.ts
  package.json
  tools/postinstall-patches.js
  tsconfig.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#1406 refactor(aspnetcore-engine): use async/await function
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/src/platform-server-utils.ts
  modules/common/engine/src/engine.ts
Labels: PR target: master-only, cla: yes

#1405 fix(builders): fix `EADDRINUSE` error on rebuilds
  modules/builders/src/ssr-dev-server/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1401 fix(builders): allow setting a public host
  modules/builders/BUILD.bazel
  modules/builders/package.json
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/schema.json
  modules/builders/src/ssr-dev-server/schema.ts
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes, comp: builders

#1403 fix(builders): error when process is closed with non zero error code
  modules/builders/src/ssr-dev-server/utils.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1408 build: use bazel `disk_cache`
  .bazelrc
  .circleci/bazel.rc
  .circleci/config.yml
Labels: PR target: master-only, cla: yes, comp: build

#1407 feat(builders): routesFile option for prerender builder
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/schema.json
  modules/builders/src/prerender/schema.ts
  modules/builders/src/prerender/utils.spec.ts
  modules/builders/src/prerender/utils.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1415 fix(common): Debug Failure. False expression: node_modules/@types/nod…
  modules/common/schematics/add/index.ts
Labels: PR target: master-only, cla: yes, comp: common

#1410 build: rename tsconfig so that the IDE can use it
  modules/builders/BUILD.bazel
  modules/builders/tsconfig.json
Labels: PR target: master-only, cla: yes

#1418 ci: improve circle ci setup
  .circleci/config.yml
Labels: PR target: master-only, cla: yes, comp: ci
