Repository angular/universal, pull requests merged in 2019-10, with the labels that each got.

#1268 refactor: simply common add schematic
  modules/common/package.json
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
  modules/common/schematics/collection.json
  modules/common/schematics/install/schema.json
  modules/common/schematics/install/schema.ts
  modules/common/schematics/testing/test-app.ts
  modules/common/schematics/utils/index.ts
  modules/common/schematics/utils/utils.ts
  modules/express-engine/schematics/install/index.ts
  modules/hapi-engine/schematics/install/index.ts
  package.json
  yarn.lock
Labels: PR target: master only, cla: yes

#1266 feat: add migrations for version 9
  modules/common/schematics/BUILD.bazel
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
  modules/common/schematics/migrations/update-9/index.spec.ts
  modules/common/schematics/migrations/update-9/index.ts
  modules/common/schematics/testing/test-app.ts
  modules/common/schematics/utils/utils.ts
  modules/express-engine/package.json
  modules/express-engine/schematics/collection.json
  modules/express-engine/schematics/install/index.spec.ts
  modules/express-engine/schematics/install/index.ts
  modules/express-engine/schematics/migrations/migration-collection.json
  modules/express-engine/schematics/migrations/update-9/index.spec.ts
  modules/express-engine/schematics/migrations/update-9/index.ts
  modules/express-engine/schematics/testing/test-app.ts
  modules/hapi-engine/package.json
  modules/hapi-engine/schematics/install/index.spec.ts
  modules/hapi-engine/schematics/install/index.ts
  modules/hapi-engine/schematics/migrations/migration-collection.json
  modules/hapi-engine/schematics/migrations/update-9/index.spec.ts
  modules/hapi-engine/schematics/migrations/update-9/index.ts
  modules/hapi-engine/schematics/testing/test-app.ts
  package.json
  yarn.lock
Labels: PR target: master only, cla: yes

#1270 docs: fix typo in version 8 update guide
  docs/v8-upgrade-guide.md
Labels: PR target: master & patch, cla: yes

#1265 refactor: remove output path logic as it's handled in universal schem…
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
  modules/common/schematics/utils/utils.ts
  modules/express-engine/schematics/install/index.ts
  modules/hapi-engine/schematics/install/index.ts
  package.json
  yarn.lock
Labels: PR target: master only, cla: yes, comp: common

#1271 fix(common): update server main option when using `ng add/ng update`
  modules/common/schematics/add/index.spec.ts
  modules/common/schematics/add/index.ts
Labels: PR target: master only, cla: yes, comp: common

#1274 fix(express-engine, hapi-engine): remove `@nguniversal/module-map-ngf…
  modules/common/schematics/BUILD.bazel
  modules/common/schematics/migrations/update-9/index.spec.ts
  modules/common/schematics/migrations/update-9/index.ts
Labels: PR target: master only, cla: yes

#1278 feat: add tslib as peerDependency
  modules/aspnetcore-engine/package.json
  modules/builders/BUILD.bazel
  modules/builders/bazel-tsconfig-build.json
  modules/common/package.json
  modules/express-engine/package.json
  modules/hapi-engine/package.json
  modules/module-map-ngfactory-loader/package.json
  modules/socket-engine/package.json
  tools/defaults.bzl
Labels: PR target: master only, cla: yes

#1280 fix(hapi-engine, express-engine): `distFolder` const should contain t…
  modules/express-engine/schematics/install/index.spec.ts
  modules/express-engine/schematics/install/index.ts
  modules/hapi-engine/schematics/install/index.spec.ts
  modules/hapi-engine/schematics/install/index.ts
Labels: PR target: master only, cla: yes, comp: express-engine, comp: hapi-engine

#1275 ci: update key cache to have more cache hits
  .circleci/config.yml
Labels: PR target: master only, cla: yes

#1281 fix: set supported node version to '>=10.13.0 <13.0.0'
  modules/aspnetcore-engine/package.json
  modules/common/package.json
  modules/express-engine/package.json
  modules/hapi-engine/package.json
  modules/module-map-ngfactory-loader/package.json
  modules/socket-engine/package.json
  package.json
Labels: cla: yes

#1285 build: update several dev dependencies
  WORKSPACE
  integration/common/package.json
  integration/express-engine-ivy/package.json
  integration/express-engine-ve/package.json
  integration/hapi-engine-ivy/package.json
  integration/hapi-engine-ve/package.json
  modules/BUILD.bazel
  modules/aspnetcore-engine/src/file-loader.ts
  modules/builders/BUILD.bazel
  modules/common/engine/src/file-loader.ts
  modules/express-engine/src/file-loader.ts
  modules/hapi-engine/src/file-loader.ts
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: PR target: master only, cla: yes, comp: build, comp: ci

#1283 ci: add renovate configuration
  renovate.json
Labels: PR target: master only, cla: yes, comp: ci

#1218 build: upgrade to @hapi/hapi
  integration/hapi-engine-ivy/package.json
  integration/hapi-engine-ivy/server.ts
  integration/hapi-engine-ve/package.json
  integration/hapi-engine-ve/server.ts
  modules/bazel-tsconfig-build.json
  modules/hapi-engine/BUILD.bazel
  modules/hapi-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
  modules/hapi-engine/schematics/install/index.spec.ts
  modules/hapi-engine/schematics/install/index.ts
  modules/hapi-engine/spec/index.spec.ts
  modules/hapi-engine/src/main.ts
  modules/hapi-engine/tokens/BUILD.bazel
  modules/hapi-engine/tokens/injection-tokens.ts
  package.json
  tools/defaults.bzl
  tools/postinstall-patches.js
  yarn.lock
Labels: PR action: review, PR target: master only, cla: yes, comp: build, comp: hapi-engine

#1306 chore: update deps
  WORKSPACE
  package.json
  yarn.lock
Labels: cla: yes

#1320 build: add --config=release to publish.sh .publish actions to guarantee version stamping
  publish.sh
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build

#1319 build: add build --nolegacy_external_runfiles to bazelrc
  .bazelrc
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build
