Repository angular/universal, pull requests merged in 2020-02, with the labels that each got.

#1488 build: update packages for release
  tools/defaults.bzl
Labels: PR target: master-only, cla: yes

#1498 Change ServerAppModule to AppServerModule
  modules/aspnetcore-engine/README.md
Labels: cla: yes

#1517 fix(builders): only remove reload script leading slash when having a …
  modules/builders/src/ssr-dev-server/index.ts
Labels: PR target: master & patch, cla: yes

#1516 build: update @types/express and http-proxy-middleware
  modules/builders/BUILD.bazel
  modules/builders/package.json
  modules/builders/src/ssr-dev-server/index.ts
  modules/express-engine/tokens/BUILD.bazel
  modules/express-engine/tokens/injection-tokens.ts
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#1519 build: Change --symlink_prefix to dist/
  .bazelrc
Labels: cla: yes

#1520 build: Update publish script
  docs/process/release.md
  publish-next.sh
  publish.sh
  scripts/package-builder.sh
Labels: cla: yes
