Repository angular/universal, pull requests merged in 2020-06, with the labels that each got.

#1719 build: use @bazel/bazelisk rather than @bazel/bazel
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes

#1725 fix(express-engine): use response in request object if not provided
  modules/express-engine/spec/index.spec.ts
  modules/express-engine/src/main.ts
  modules/express-engine/testing/mock.server.module.ts
Labels: cla: yes

#1728 docs: remove redundant sections and broken link
  README.md
Labels: PR target: master-only, cla: yes

#1731 build: remove dev dependency on @types/express-serve-static-core
  modules/express-engine/tokens/BUILD.bazel
  modules/express-engine/tokens/injection-tokens.ts
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build

#1743 tests: update tests to work with version 10
  modules/common/schematics/add/index.spec.ts
  modules/express-engine/schematics/install/index.spec.ts
  modules/express-engine/schematics/migrations/update-9/index.spec.ts
  modules/hapi-engine/schematics/install/index.spec.ts
  modules/hapi-engine/schematics/migrations/update-9/index.spec.ts
Labels: PR target: master-only, cla: yes
