Repository angular/universal, pull requests merged in 2020-09, with the labels that each got.

#1823 build: remove --experimental_allow_incremental_repository_updates in …
  .bazelrc
Labels: cla: yes

#1824 build: update angular deps to version 11
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: PR target: master-only, cla: yes

#1829 ci: update puppeteer
  .circleci/config.yml
  package.json
  yarn.lock
Labels: cla: yes

#1840 build: update tslint rules to remove usage of whitelist in comments
  tools/tslint-rules/noRxjsPatchImportsRule.ts
Labels: PR action: merge, PR target: master & patch, cla: yes, comp: build

#1841 style: fix typo in comment
  tools/tslint-rules/noRxjsPatchImportsRule.ts
Labels: cla: yes

#1842 ci: update configuration to use new CircleCI docker images
  .circleci/config.yml
Labels: PR target: master & patch, cla: yes

#1845 refactor: remove usage on `@schematics/angular` old json helpers
  modules/common/schematics/add/index.ts
Labels: PR target: master-only, cla: yes

#1847 docs: fix typo
  docs/transfer-http.md
Labels: PR action: merge, PR state: LGTM, PR target: master-only, cla: yes, comp: docs
