Repository angular/universal, pull requests merged in 2020-01, with the labels that each got.

#1396 feat(builders): parallelize renders in prerender builder
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/render.ts
  modules/builders/src/prerender/schema.json
  modules/builders/src/prerender/schema.ts
  modules/builders/src/prerender/utils.spec.ts
  modules/builders/src/prerender/utils.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1426 feat(builders): extract routes with guess-js
  modules/builders/BUILD.bazel
  modules/builders/package.json
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/models.ts
  modules/builders/src/prerender/schema.json
  modules/builders/src/prerender/schema.ts
  modules/builders/src/prerender/utils.spec.ts
  modules/builders/src/prerender/utils.ts
  package.json
  yarn.lock
Labels: PR target: master-only, cla: yes, comp: builders

#1431 ci: add alan-agius4 as builders package code owner
  .github/CODEOWNERS
Labels: PR target: master-only, cla: yes, comp: ci

#1435 test: refactor to use npm cli packages from workspace
  integration/express-engine-ivy-prerender/package.json
  integration/express-engine-ivy/package.json
  integration/express-engine-ve/package.json
  integration/hapi-engine-ivy/package.json
  integration/hapi-engine-ve/package.json
Labels: PR target: master-only, cla: yes

#1439 docs: update issue templates
  .github/ISSUE_TEMPLATE/Bug.md
  .github/ISSUE_TEMPLATE/Feature_Request.md
Labels: PR target: master-only, cla: yes

#1463 chore: replace vikram with keen in codeowners
  .github/CODEOWNERS
  README.md
Labels: cla: yes

#1462 fix(builders): send `X-Forwarded` headers when using ssr-dev-server
  modules/builders/src/ssr-dev-server/index.spec.ts
  modules/builders/src/ssr-dev-server/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1465 build: update nodejs rules to 1.0+
  WORKSPACE
  modules/builders/BUILD.bazel
  modules/common/BUILD.bazel
  modules/common/schematics/BUILD.bazel
  modules/express-engine/BUILD.bazel
  modules/express-engine/schematics/BUILD.bazel
  modules/hapi-engine/BUILD.bazel
  modules/hapi-engine/schematics/BUILD.bazel
  package.json
  scripts/package-builder.sh
  tools/defaults.bzl
  yarn.lock
Labels: PR target: master-only, cla: yes, comp: build

#1467 fix(builders): default to a minimum of 1 CPU when sharding builds
  modules/builders/src/prerender/utils.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1472 build: change bazel nodejs rules to `~`
  package.json
  yarn.lock
Labels: cla: yes

#1475 feat(prerender): add "/" as the default route in angular.json
  modules/common/schematics/add/index.ts
Labels: PR target: master-only, cla: yes, comp: builders

#1464 test: disable flaky ci test
  modules/builders/src/ssr-dev-server/index.spec.ts
Labels: PR target: master-only, cla: yes

#1476 ci: reduce ci steps
  .circleci/config.yml
Labels: PR target: master-only, cla: yes, comp: ci
