Repository angular/universal, pull requests merged in 2020-04, with the labels that each got.

#1592 tests: remove module from tsconfig.server.json
  integration/express-engine-ivy-prerender/tsconfig.server.json
  integration/express-engine-ivy/tsconfig.server.json
  integration/express-engine-ve/tsconfig.server.json
  integration/hapi-engine-ivy/tsconfig.server.json
  integration/hapi-engine-ve/tsconfig.server.json
Labels: PR target: master-only, cla: yes

#1612 📝 docs: fix existing typo in readme
  README.md
Labels: cla: yes

#1605 fix(prerender): use browser builder's index option
  integration/express-engine-ivy-prerender/angular.json
  modules/builders/BUILD.bazel
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/render.ts
  modules/builders/src/prerender/utils.spec.ts
  modules/builders/src/prerender/utils.ts
Labels: PR action: merge, PR target: master-only, cla: yes

#1647 [master] @nguniversal/builders package improvements
  modules/builders/package.json
Labels: cla: yes
