Repository angular/universal, pull requests merged in 2020-10, with the labels that each got.

#1866 ci: bump to lastest sha of angular/dev-infra's lock-closed action
  .github/workflows/lock-closed.yml
Labels: cla: yes

#1868 build: update `lock-closed` GitHub action to latest version
  .github/workflows/lock-closed.yml
Labels: PR target: master-only, cla: yes

#1872 build: update puppeteer to version 5.4.0
  .circleci/config.yml
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#1809 build: update build_bazel_rules_nodejs to 2.0.2
  .bazelversion
  WORKSPACE
  modules/BUILD.bazel
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes

#1875 build: update angular packages to version 11
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: PR target: master-only, cla: yes

#1877 fix(builders): improve prerendering logging
  modules/builders/BUILD.bazel
  modules/builders/package.json
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/render.ts
  package.json
  yarn.lock
Labels: PR action: merge, PR target: master-only, cla: yes
