Repository angular/universal, pull requests merged in 2021-11, with the labels that each got.

#2426 docs: update `CHANGELOG` for `v13.0.0`
  CHANGELOG.md
Labels: action: merge, cla: yes, target: rc

#2428 docs: update `CHANGELOG` with `v13.1.0-next.0` release notes
  CHANGELOG.md
Labels: cla: yes, target: minor

#2432 fix(@nguniversal/express-engine): initialNavigation should be 'enabledBlocking'
  modules/express-engine/schematics/utils/utils.ts
Labels: action: merge, cla: yes, target: patch

#2435 fix(@nguniversal/common): correctly handle lazy loaded routes in Clover
  integration/clover/src/app/app-routing.module.ts
  integration/clover/src/app/lazy/lazy-routing.module.ts
  integration/clover/src/app/lazy/lazy.component.css
  integration/clover/src/app/lazy/lazy.component.html
  integration/clover/src/app/lazy/lazy.component.spec.ts
  integration/clover/src/app/lazy/lazy.component.ts
  integration/clover/src/app/lazy/lazy.module.ts
  integration/clover/test.js
  modules/common/clover/server/src/custom-resource-loader.ts
Labels: action: merge, cla: yes, target: patch

#2440 docs: add v13.0.1 entry to `CHANGELOG.md`
  CHANGELOG.md
Labels: action: merge, cla: yes, target: patch

#2447 build: update ng-dev configuration for release
  .bazelrc
  .ng-dev/release.ts
  publish.sh
  scripts/package-builder.js
  tools/bazel-stamp-vars.js
Labels: action: merge, cla: yes, target: patch

#2450 docs: update release docs to reflect new tooling
  docs/process/release.md
Labels: action: merge, cla: yes, target: patch
