Repository angular/universal, pull requests merged in 2021-02, with the labels that each got.

#1966 refactor: delete `@nguniversal/module-map-ngfactory-loader`
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/Feature_Request.md
  .ng-dev/release.ts
  modules/module-map-ngfactory-loader/BUILD.bazel
  modules/module-map-ngfactory-loader/README.md
  modules/module-map-ngfactory-loader/index.ts
  modules/module-map-ngfactory-loader/package.json
  modules/module-map-ngfactory-loader/public_api.ts
  modules/module-map-ngfactory-loader/spec/index.spec.ts
  modules/module-map-ngfactory-loader/src/index.ts
  modules/module-map-ngfactory-loader/src/module-map-loader.module.ts
  modules/module-map-ngfactory-loader/src/module-map-ngfactory-loader.ts
  modules/module-map-ngfactory-loader/src/module-map.ts
Labels: cla: yes, target: minor

#1965 build: update to bazel 4
  .bazelrc
  .bazelversion
  WORKSPACE
Labels: action: merge, cla: yes, target: patch

#1964 build: update puppeteer to version 6
  .circleci/config.yml
  package.json
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#1971 fix(@nguniversal/hapi-engine): fix incorrect peer dependency on hapi
  modules/hapi-engine/package.json
Labels: action: merge, cla: yes, target: patch

#1975 fix(@nguniversal/common-engine): ReferenceError: URL is not defined
  modules/common/engine/src/engine.ts
Labels: action: merge, cla: yes, target: patch

#1976 build: bump version on master to v12.0.0-next.0
  package.json
  renovate.json
Labels: action: merge, cla: yes, target: major

#1982 refactor(@nguniversal/common): use fs.promises instead of promisify
  modules/common/engine/src/engine.ts
  modules/common/engine/src/file-loader.ts
  modules/common/engine/src/inline-css-processor.ts
  modules/common/engine/src/utils.ts
Labels: cla: yes, target: major

#1983 feat(@nguniversal/builders) add SSL support for dev-server
  modules/builders/src/ssr-dev-server/index.spec.ts
  modules/builders/src/ssr-dev-server/index.ts
  modules/builders/src/ssr-dev-server/schema.json
  modules/builders/src/ssr-dev-server/schema.ts
Labels: cla: yes, target: major

#1984 build: update Angular versions to v11.2
  modules/builders/src/prerender/index.ts
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, cla: yes, target: rc

#1981 fix(@nguniversal/builders): fix development mode ignored stdout message
  modules/builders/src/ssr-dev-server/index.ts
Labels: action: merge, cla: yes, target: patch

#1991 build: update Angular packages to version 11.2
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, cla: yes, target: rc

#1990 build: update Angular packages to version 12
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, cla: yes, target: major

#2004 fix(@nguniversal/common): inline critical font-face rules when using critical css inlining
  modules/builders/src/prerender/index.ts
  modules/common/engine/src/inline-css-processor.ts
Labels: action: merge, cla: yes, target: patch
