Repository angular/universal, pull requests merged in 2021-08, with the labels that each got.

#2235 ci: replace Keen with Doug in GitHub CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes, target: minor

#2236 docs: Replace Keen with Doug as Angular Core API contact
  README.md
Labels: action: merge, cla: yes, target: minor

#2242 ci: configure renovate to manage GitHub workflow updates
  renovate.json
Labels: action: merge, cla: yes, target: major

#2250 fix: remove the toPromise()
  modules/common/src/transfer_http.ts
Labels: action: merge, cla: yes, target: major

#2254 test(@nguniversal/common): fix lint issues
  modules/common/src/transfer_http.ts
Labels: cla: yes, target: minor

#2257 build: update master to `13.0.0-next.0`
  package.json
Labels: action: merge, cla: yes, target: minor

#2256 build: update release notes to be generated using ng-dev
  .ng-dev/config.ts
  .ng-dev/release.ts
  CHANGELOG.md
  docs/process/release.md
Labels: action: merge, cla: yes, target: minor
