Repository angular/universal, pull requests merged in 2021-05, with the labels that each got.

#2085 build: fix stamping
  BUILD.bazel
  tools/defaults.bzl
Labels: action: merge, cla: yes, target: rc

#2102 docs: remove outdated roadmap
  README.md
Labels: action: merge, cla: yes, target: rc

#2117 fix(@nguniversal/common): add Window stubs to Engine (Clover)
  modules/common/clover/server/src/server-engine.ts
  modules/common/clover/server/src/stubs.ts
Labels: action: merge, cla: yes, target: patch

#2116 fix(@nguniversal/common): correctly construct host string
  modules/common/clover/server/src/server-engine.ts
  modules/common/schematics/ng-add/files/src/server.ts.template
Labels: action: merge, cla: yes, target: patch

#2123 fix(common): add `serverTarget` for prerender
  modules/express-engine/schematics/install/index.ts
Labels: action: merge, cla: yes, target: patch

#2124 refactor(express-engine): use `projectName` for prerender
  modules/express-engine/schematics/install/index.ts
Labels: action: merge, cla: yes, target: patch

#2128 docs: add a link of the contributing guidelines to README
  README.md
Labels: action: merge, cla: yes, target: minor
