Repository angular/universal, pull requests merged in 2021-01, with the labels that each got.

#1938 test: add unit test for aspnet engine
  modules/aspnetcore-engine/BUILD.bazel
  modules/aspnetcore-engine/spec/index.spec.ts
  modules/aspnetcore-engine/src/main.ts
  modules/aspnetcore-engine/testing/mock.server.module.ts
Labels: cla: yes, target: minor

#1939 refactor(common): mark private methods with private keyword
  modules/common/engine/src/engine.ts
Labels: cla: yes, target: minor

#1943 docs: fix typo in engine name
  modules/aspnetcore-engine/README.md
Labels: cla: yes, target: minor

#1947 refactor: remove redundant catch block error variable
  modules/common/engine/src/utils.ts
Labels: action: merge, cla: yes, target: minor

#1937 fix the warning on lock-closed gh-actions: Warning: Unexpected input(s) 'lock-bot-key'
  .github/workflows/lock-closed.yml
Labels: action: cleanup, cla: yes

#1951 build: setup ng-dev tooling to perform merges
  .ng-dev/config.ts
  .ng-dev/github.ts
  .ng-dev/merge.ts
  .ng-dev/release.ts
  package.json
  yarn.lock
Labels: action: merge, cla: yes, target: minor

#1950 fix(@nguniversal/aspnetcore-engine): correctly set publicPath
  modules/aspnetcore-engine/src/main.ts
Labels: action: merge, cla: yes, target: patch

#1953 test: remove extra dependency
  integration/common/package.json
  integration/common/src/helloworld/client.ts
Labels: action: merge, cla: yes, target: patch

#1957 ci: add commit message validation
  .circleci/config.yml
  .ng-dev/commit-message.ts
  .ng-dev/config.ts
  .ng-dev/release.ts
Labels: action: merge, cla: yes, target: minor
