Repository angular/universal, pull requests merged in 2021-10, with the labels that each got.

#2335 docs: update changelog with 12.1.1 release
  CHANGELOG.md
Labels: action: merge, cla: yes, target: major

#2349 feat(@nguniversal/common): disable critical CSS inlining by default
  modules/common/clover/server/src/server-engine.ts
  modules/common/engine/src/engine.ts
Labels: action: merge, cla: yes, target: major, flag: breaking change

#2372 build: remove unused `jest-worker` dependency
  package.json
  yarn.lock
Labels: cla: yes, target: major

#2380 build: update Bazel Node.js version to `14.17.1`
  WORKSPACE
Labels: action: merge, cla: yes, target: minor

#2386 docs: update `CHANGELOG.md` with `v13.0.0-rc.0`
  CHANGELOG.md
Labels: action: merge, cla: yes, target: rc

#2387 docs: update release changelog generation process.
  docs/process/release.md
Labels: action: merge, cla: yes, target: rc

#2417 build: update node engines to not error on Node.Js 17
  modules/aspnetcore-engine/package.json
  modules/builders/package.json
  modules/common/package.json
  modules/express-engine/package.json
  modules/hapi-engine/package.json
  modules/socket-engine/package.json
Labels: action: merge, cla: yes, target: rc
