Repository angular/universal, pull requests merged in 2022-06, with the labels that each got.

#2674 release: cut the v14.0.0-rc.1 release
  CHANGELOG.md
Labels: comp: build, action: merge

#2678 docs: release notes for the v14.0.0 release
  CHANGELOG.md
Labels: action: merge, target: minor

#2679 build: update angular
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  package.json
  yarn.lock
Labels: action: merge, target: patch

#2683 fix(@nguniversal/common): correctly handle headers for jsdom in Clover
  modules/common/clover/server/src/custom-resource-loader.ts
  modules/common/clover/server/src/server-engine.ts
Labels: action: merge, target: patch

#2696 build: update angular packages to 14.1.0-next
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge, target: minor

#2697 Bump version to "v14.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch

#2698 docs: release notes for the v14.0.1 release
  CHANGELOG.md
Labels: action: merge, target: minor

#2700 Bump version to "v14.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, target: minor

#2705 build: update ng-dev and account for ESM-config changes
  .ng-dev/commit-message.mts
  .ng-dev/config.mts
  .ng-dev/config.ts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  .ng-dev/tsconfig.json
  package.json
  scripts/package-builder.d.ts
  scripts/package-builder.js
  yarn.lock
Labels: action: merge, target: minor

#2712 build: update ng-dev and account for ESM-config changes
  .ng-dev/commit-message.mts
  .ng-dev/config.mts
  .ng-dev/config.ts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  .ng-dev/tsconfig.json
  package.json
  scripts/package-builder.d.ts
  scripts/package-builder.js
  yarn.lock
Labels: action: merge, target: patch

#2711 build: avoid use of ts-node wrapper script as it breaks child process forking
  package.json
  yarn.lock
Labels: action: merge, target: patch

#2709 fix(@nguniversal/builders): correctly handle path normalizations on Windows
  modules/builders/src/prerender/index.ts
  modules/builders/src/static-generator/index.ts
Labels: action: merge, target: patch

#2716 docs: release notes for the v14.0.2 release
  CHANGELOG.md
Labels: action: merge, target: minor

#2717 Bump version to "v14.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor

#2724 build: update contributing guide to reflect branch name of `code-of-conduct` repository
  CONTRIBUTING.md
Labels: action: merge, target: patch
