Repository angular/universal, pull requests merged in 2022-03, with the labels that each got.

#2478 docs(@nguniversal/builders): Added Builder Readme Overview
  modules/builders/README.md
Labels: action: merge, target: patch

#2568 feat(@nguniversal/common): drop support for Node.js 12
  modules/builders/package.json
  modules/common/package.json
  modules/express-engine/package.json
  package.json
  yarn.lock
Labels: target: major, flag: breaking change

#2570 fix(express-engine): construct req url instead of using originalUrl
  modules/express-engine/src/main.ts
Labels: action: merge, comp: express-engine, target: major

#2571 ci: fix permissions and tags
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  .github/workflows/scorecard.yml
Labels: action: merge, target: major

#2582 build: update to TypeScript 4.6
  modules/common/clover/src/transfer-http-cache/transfer-http-cache.interceptor.ts
  modules/common/src/transfer_http.ts
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: action: merge

#2585 refactor: update `master` branch to `13.2.0-next.0`
  package.json
Labels: action: merge, target: minor

#2589 Bump version to "v13.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor
