Repository angular/universal, pull requests merged in 2022-11, with the labels that each got.

#2889 Bump version to "v14.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch

#2891 Bump version to "v15.0.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc

#2896 fix(@nguniversal/common): mark `bootstrap` in `RenderOptions` as non required
  modules/common/engine/src/engine.ts
  modules/express-engine/src/main.ts
Labels: action: merge, target: patch

#2898 Bump version to "v14.2.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#2900 Bump version to "v15.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#2901 docs: release notes for the v15.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, area: docs

#2905 fix(@nguniversal/express-engine): fix formatting in generated `server.ts`
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: action: merge, target: patch

#2910 fix(@nguniversal/builders): Initialize zone.js once in rendering workers
  modules/builders/BUILD.bazel
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/worker.ts
Labels: action: merge, target: patch

#2913 Bump version to "v15.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc

#2916 Bump version to "v15.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc

#2917 docs: release notes for the v15.0.0 release
  CHANGELOG.md
Labels: action: merge, target: minor, area: docs

#2925 Bump version to "v14.2.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#2926 docs: release notes for the v14.2.3 release
  CHANGELOG.md
Labels: action: merge, area: docs

#2796 docs: readme update
  README.md
Labels: action: merge, type: docs, target: minor, area: docs
