Repository angular/universal, pull requests merged in 2022-10, with the labels that each got.

#2841 feat(@nguniversal/builders): add sourcemap mapping support for dev-server
  modules/builders/src/ssr-dev-server/index.ts
Labels: action: merge, target: minor

#2787 build: run integration tests with bazel
  .bazelignore
  .circleci/config.yml
  .gitignore
  BUILD.bazel
  WORKSPACE
  integration/clover/BUILD.bazel
  integration/clover/test.sh
  integration/common-engine/BUILD.bazel
  integration/common-engine/e2e/protractor.conf.js
  integration/common-engine/test.sh
  integration/express-engine-ivy-hybrid/BUILD.bazel
  integration/express-engine-ivy-hybrid/e2e/protractor.conf.js
  integration/express-engine-ivy-hybrid/test.sh
  integration/express-engine-ivy/BUILD.bazel
  integration/express-engine-ivy/e2e/protractor.conf.js
  integration/express-engine-ivy/test.sh
  modules/builders/BUILD.bazel
  modules/common/BUILD.bazel
  modules/express-engine/BUILD.bazel
  package.json
  yarn.lock
Labels: action: merge, target: minor

#2856 Bump version to "v15.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#2853 ci: remove integration tests from seperate step
  .circleci/config.yml
Labels: action: merge, target: minor

#2859 build: replace `@angular/dev-infra-private` with `@angular/ng-dev`
  .ng-dev/commit-message.mts
  .ng-dev/format.mts
  .ng-dev/github.mts
  .ng-dev/pull-request.mts
  .ng-dev/release.mts
  package.json
  yarn.lock
Labels: action: merge, target: minor

#2862 docs: update transfer-http docs
  docs/transfer-http.md
Labels: action: merge, target: minor, area: docs

#2861 fix(@nguniversal/builders): import `zone.js` in worker during prerendering
  modules/builders/src/prerender/index.ts
  modules/builders/src/prerender/worker.ts
  modules/builders/testing/hello-world-app/src/main.server.ts
Labels: action: merge, target: patch

#2860 build: delete un-needed dependencies
  integration/clover/angular.json
  integration/common-engine/angular.json
  integration/common-engine/e2e/protractor.conf.js
  integration/common-engine/package.json
  integration/express-engine-ivy-hybrid/e2e/protractor.conf.js
  integration/express-engine-ivy-hybrid/package.json
  integration/express-engine-ivy/angular.json
  integration/express-engine-ivy/e2e/protractor.conf.js
  integration/express-engine-ivy/package.json
  modules/builders/testing/hello-world-app/angular.json
  package.json
  yarn.lock
Labels: action: merge, target: minor

#2868 build: update dependencies in `@nguniversal/builders`
  modules/builders/package.json
Labels: action: merge, target: minor

#2879 fix(@nguniversal/builders): address method Promise.prototype.then called on incompatible receiver error
  modules/builders/BUILD.bazel
  modules/builders/src/prerender/worker.ts
Labels: action: merge, target: minor

#2877 fix(@nguniversal/express-engine): replace zone.js import
  integration/common-engine/server.ts
  integration/express-engine-ivy-hybrid/server.ts
  integration/express-engine-ivy/server.ts
  modules/builders/testing/hello-world-app/server.ts
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: action: merge, target: patch
