Repository angular/universal, pull requests merged in 2022-05, with the labels that each got.

#2630 build: clean up references to old `master` branch
  .github/ISSUE_TEMPLATE/Bug.md
  .github/PULL_REQUEST_TEMPLATE/Improvement.md
  .github/PULL_REQUEST_TEMPLATE/New_Feature.md
  CONTRIBUTING.md
  README.md
  docs/angular2-universal-migration.md
  integration/clover/README.md
  integration/common-engine/README.md
  integration/express-engine-ivy-hybrid/README.md
  integration/express-engine-ivy-hybrid/server.ts
  integration/express-engine-ivy/README.md
  integration/express-engine-ivy/server.ts
  modules/builders/testing/hello-world-app/README.md
  modules/common/README.md
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: action: merge, target: minor

#2632 Bump version to "v13.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch

#2633 docs: release notes for the v13.1.1 release
  CHANGELOG.md
Labels: action: merge, target: major

#2634 build: bumps version of `main` branch to `14.0.0-next.0` so the next release will be v14, not v13.2
  package.json
Labels: action: merge, target: major

#2636 Bump version to "v14.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge, target: major

#2646 build: update TypeScript to 4.7.1-rc
  package.json
  yarn.lock
Labels: action: merge, target: rc

#2645 Bump version to "v14.0.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc

#2651 docs: release notes for the v14.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, target: minor

#2664 refactor: update paths to use new API of `@schematics/angular`
  modules/common/schematics/ng-add/index.ts
  modules/express-engine/schematics/install/index.ts
  modules/express-engine/schematics/utils/utils.ts
Labels: action: merge, target: rc

#2665 build: set up post approval changes commit action
  .github/workflows/dev-infra.yml
Labels: action: merge, target: patch

#2673 Bump version to "v14.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc
