Repository angular/universal, pull requests merged in 2022-01, with the labels that each got.

#2492 chore: bump year
  LICENSE
Labels: action: merge, target: patch

#2502 Ensure CommonJS migrations can be accessed
  modules/common/schematics/BUILD.bazel
  modules/common/schematics/ng-add/files/src/server.ts.template
  modules/common/schematics/package.json
  modules/express-engine/schematics/BUILD.bazel
  modules/express-engine/schematics/package.json
Labels: action: merge, target: patch

#2506 Bump version to "v13.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: patch

#2510 Bump version to "v13.0.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#2511 docs: release notes for the v13.0.2 release
  CHANGELOG.md
Labels: action: merge, target: minor

#2512 Bump version to "v13.1.0-next.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: minor
