Repository angular/universal, pull requests merged in 2023-04, with the labels that each got.

#3067 feat(@nguniversal/express-engine): add standalone support to `ng add`
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
  modules/express-engine/schematics/install/index.spec.ts
  modules/express-engine/schematics/install/index.ts
  modules/express-engine/schematics/testing/test-app.ts
Labels: action: merge, target: major, detected: feature

#3070 Bump version to "v16.0.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#3072 fix(@nguniversal/express-engine): update import for template server file
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
  modules/express-engine/schematics/install/index.spec.ts
Labels: action: merge, target: rc

#3078 build: update minimum supported Node version from 16.13.0 -> 16.14.0
  .circleci/config.yml
  WORKSPACE
  modules/builders/package.json
  modules/common/package.json
  modules/express-engine/package.json
  package.json
Labels: area: build & ci, action: merge, target: rc

#3079 refactor(@nguniversal/common): remove usage of `BrowserTransferStateModule`
  docs/transfer-http.md
  modules/common/clover/src/transfer-http-cache/transfer-http-cache.module.ts
Labels: action: merge, target: rc

#3083 build: build packages in APF version 16 format
  .bazelversion
  WORKSPACE
  modules/bazel-tsconfig-build.json
  package.json
  tools/defaults.bzl
  tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
  tools/postinstall/patches/@bazel+concatjs+5.8.1.patch
  tsconfig.json
  yarn.lock
Labels: area: build & ci, action: merge, target: rc

#3081 fix(@nguniversal/builders): add support to serve service workers
  modules/builders/src/ssr-dev-server/index.spec.ts
  modules/builders/src/ssr-dev-server/index.ts
Labels: action: merge, target: patch

#3057 fix(@nguniversal/common): update TransferHttpResponse requiring body and headers
  modules/common/clover/src/transfer-http-cache/transfer-http-cache.interceptor.ts
  modules/common/src/transfer_http.ts
Labels: action: merge, target: rc

#3084 refactor(@nguniversal/common): simplify `TransferHttpCacheInterceptor` intercept logic
  modules/common/clover/src/transfer-http-cache/transfer-http-cache.interceptor.ts
Labels: action: merge, target: rc

#3089 Bump version to "v15.2.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3090 docs: release notes for the v15.2.1 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3092 docs: release notes for the v16.0.0-rc.0 release
  CHANGELOG.md
Labels: action: merge, target: minor, area: docs

#3093 fix(@nguniversal/express-engine): export default bootstrap in server template for standalone apps
  modules/express-engine/schematics/install/files/__serverFileName@stripTsExtension__.ts
Labels: action: merge, area: express-engine, target: rc

#3100 Bump version to "v16.0.0-rc.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3101 docs: release notes for the v16.0.0-rc.1 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3109 ci: remove lock closed
  .github/workflows/lock-closed.yml
Labels: area: build & ci

#3110 Bump version to "v16.0.0-rc.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3111 docs: release notes for the v16.0.0-rc.2 release
  CHANGELOG.md
Labels: action: merge, area: docs
