Repository angular/universal, pull requests merged in 2023-08, with the labels that each got.

#3217 build: update critters
  modules/common/package.json
  package.json
  yarn.lock
Labels: area: build & ci, action: merge, target: patch

#3218 Bump version to "v16.1.2" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3219 docs: release notes for the v16.1.2 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3220 Bump version to "v16.2.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3222 refactor: update changelog link for Critters version bump
  CHANGELOG.md
Labels: action: merge, target: minor

#3223 refactor: update changelog link for Critters version bump
  CHANGELOG.md
Labels: action: merge, target: rc

#3224 refactor: update changelog link for Critters version bump
  CHANGELOG.md
Labels: action: merge, target: patch

#3225 refactor: update changelog link for Critters version bump
  CHANGELOG.md
Labels: action: merge, target: minor

#3226 Configure next branch to receive major changes for v17.0.0-next.0
  package.json
Labels: action: merge, target: minor

#3209 docs: update the http tag with https in contributing file
  CONTRIBUTING.md
Labels: action: merge, target: patch, area: docs

#3230 fix(@nguniversal/common): check for server context when doing hybrid rendering
  modules/common/engine/src/engine.ts
Labels: action: merge, target: patch

#3231 Bump version to "v16.1.3" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3236 build: update angular
  .github/workflows/dev-infra.yml
  modules/builders/package.json
  package.json
  yarn.lock
Labels: area: build & ci, action: merge, target: rc

#3237 Bump version to "v16.2.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3238 docs: release notes for the v16.2.0 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3243 fix(@nguniversal/common): error during critical CSS inlining for external stylesheets
  modules/common/tools/src/inline-css-processor.ts
Labels: action: merge, target: patch
