Repository angular/universal, pull requests merged in 2023-06, with the labels that each got.

#3159 refactor: deprecate transfer http cache
  modules/common/src/state-transfer-initializer/README.md
  modules/common/src/state-transfer-initializer/module.ts
  modules/common/src/transfer_http.ts
Labels: action: merge, target: minor, detected: deprecation

#3165 Bump version to "v16.1.0-rc.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3173 Bump version to "v16.1.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge, target: rc

#3174 docs: release notes for the v16.1.0 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3182 build: update dependency critters to v0.0.19
  modules/builders/src/prerender/index.spec.ts
  modules/common/package.json
  package.json
  yarn.lock
Labels: area: build & ci, action: merge, target: patch

#3184 Bump version to "v16.1.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3185 docs: release notes for the v16.1.1 release
  CHANGELOG.md
Labels: action: merge, area: docs
