Repository angular/universal, pull requests merged in 2023-05, with the labels that each got.

#3116 build: update angular
  .github/workflows/dev-infra.yml
  integration/common-engine/angular.json
  integration/express-engine-csp-nonce/angular.json
  integration/express-engine-ivy-hybrid/angular.json
  integration/express-engine-ivy/angular.json
  integration/express-engine-standalone/angular.json
  modules/builders/testing/hello-world-app/angular.json
  package.json
  yarn.lock
Labels: action: merge, target: minor

#3117 Bump version to "v16.0.0" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3118 docs: release notes for the v16.0.0 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3123 fix(@nguniversal/builders): strip out newlines
  modules/builders/src/ssr-dev-server/index.spec.ts
  modules/builders/src/ssr-dev-server/index.ts
Labels: action: merge, target: patch

#3126 Bump version to "v16.0.1" with changelog.
  CHANGELOG.md
  package.json
Labels: action: merge

#3127 docs: release notes for the v16.0.1 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3135 fix(@nguniversal/common): correctly handle multiple lazy CSS files
  integration/express-engine-ivy/angular.json
  integration/express-engine-ivy/e2e/src/app.e2e-spec.ts
  integration/express-engine-ivy/src/styles-extra.css
  modules/common/engine/src/engine.ts
Labels: action: merge, area: common, target: patch

#3139 docs: release notes for the v16.0.2 release
  CHANGELOG.md
Labels: action: merge, area: docs

#3143 build: update Angular deps to version 16.1
  modules/builders/package.json
  modules/common/package.json
  modules/express-engine/package.json
Labels: area: build & ci, action: merge, target: minor

#3144 Bump version to "v16.1.0-next.0" with changelog.
  CHANGELOG.md
Labels: action: merge

#3153 build: update dependency critters to v0.0.17
  modules/builders/src/prerender/index.spec.ts
  modules/builders/src/prerender/worker.ts
  modules/common/clover/server/src/server-engine.ts
  modules/common/engine/src/engine.ts
  modules/common/package.json
  package.json
  yarn.lock
Labels: area: build & ci, action: merge, target: minor
