Repository angular/universal, pull requests merged in 2023-01, with the labels that each got.

#2963 build: fix scorecard action failing
  .github/workflows/scorecard.yml
Labels: area: build & ci

#2964 build: fix scorecard action signing
  .github/workflows/scorecard.yml
Labels: area: build & ci

#2974 ci: update `circleci/browser-tools` to `1.4.0`
  .circleci/config.yml
Labels: area: build & ci, action: merge, target: patch

#2975 build: remove `defaults.bzl` version in favor of version in `package.json`
  modules/builders/package.json
  modules/common/package.json
  modules/express-engine/package.json
  tools/defaults.bzl
Labels: action: merge, target: minor

#2977 build: update angular
  .github/workflows/dev-infra.yml
  .github/workflows/lock-closed.yml
  modules/builders/package.json
  package.json
  yarn.lock
Labels: area: build & ci

#2984 build: update dev-infra packages
  package.json
  tools/defaults.bzl
  yarn.lock
Labels: area: build & ci, action: merge, target: patch

#2990 build: remove minimatch as it's unused
  package.json
  yarn.lock
Labels: area: build & ci, action: merge, target: patch

#2989 ci: disable Renovate updates for `@angular/bazel`
  renovate.json
Labels: area: build & ci, target: patch
